"""
This type stub file was generated by pyright.
"""

import mlx.nn as nn
from pathlib import Path
from typing import Any, Dict, Optional, Union

"""Standalone loader for sidecar-file MTP (Multi-Token Prediction) checkpoints.

Some MTP checkpoints (e.g. those produced by the third-party "MTPLX" tool)
ship the MTP head's weights in a separate ``mtp.safetensors`` file next to a
model's main shards, instead of bundling them into ``model*.safetensors``.
``mlx_lm.utils.load_model`` only ever looks at files matching the
``model*.safetensors`` glob, so such a checkpoint loads with a freshly
initialized (i.e. untrained/random) MTP head whenever its config declares
``mtp_num_hidden_layers > 0`` -- see ``qwen3_5.TextModel.sanitize`` for how the
default "strip mtp.* weights" behavior is gated so this doesn't raise.

``load_mtp_head`` fills that gap: given a model directory (or Hugging Face
repo id) and an already-loaded model instance, it locates the sidecar file,
builds/attaches an ``MTPModule`` if one is not already present, quantizes the
numbered-expert MoE weights to match the sidecar's own pre-quantized format,
and loads every tensor by name.

The MTP module design (``MTPModule`` / ``MTPDecoderLayer`` in ``qwen3_5.py``,
and ``TextModel.mtp_forward`` / ``TextModel.make_mtp_cache``) follows
ml-explore/mlx-lm PR #990 (AirRunner, "feat/mtp-native", Apache-2.0). This
module -- the sidecar loader itself -- is new: it is not part of that PR. The
sidecar tensor-name and quantization convention it expects was determined
from a real checkpoint's config.json (``mtplx_mtp_expected_keys`` /
``mtplx_mtp_quantization`` / ``mlx_lm_extra_tensors``) and the
``mtp.safetensors`` file's own safetensors header, e.g.
https://huggingface.co/Youssofal/Qwen3.6-35B-A3B-MTPLX-Optimized-Speed

Sidecar tensor-name mapping (all keys below use a leading "mtp." prefix,
stripped before loading into the MTPModule submodule tree):

    mtp.fc.weight                                        -> fc.weight (float)
    mtp.pre_fc_norm_hidden.weight                        -> pre_fc_norm_hidden.weight (float)
    mtp.pre_fc_norm_embedding.weight                     -> pre_fc_norm_embedding.weight (float)
    mtp.norm.weight                                      -> norm.weight (float)
    mtp.layers.{L}.input_layernorm.weight                -> layers.{L}.input_layernorm.weight (float)
    mtp.layers.{L}.post_attention_layernorm.weight       -> layers.{L}.post_attention_layernorm.weight (float)
    mtp.layers.{L}.self_attn.{q,k,v,o}_proj.weight       -> layers.{L}.self_attn.{q,k,v,o}_proj.weight (float)
    mtp.layers.{L}.self_attn.{q,k}_norm.weight           -> layers.{L}.self_attn.{q,k}_norm.weight (float)
    mtp.layers.{L}.mlp.gate.weight                       -> layers.{L}.mlp.gate.weight (float, router)
    mtp.layers.{L}.mlp.shared_expert.{gate,up,down}_proj.weight
                                                          -> layers.{L}.mlp.shared_expert.{gate,up,down}_proj.weight (float)
    mtp.layers.{L}.mlp.shared_expert_gate.weight         -> layers.{L}.mlp.shared_expert_gate.weight (float)
    mtp.layers.{L}.mlp.experts.{E}.{gate,up,down}_proj.{weight,scales,biases}
                                                          -> stacked over E into
                                                             layers.{L}.mlp.switch_mlp.{gate,up,down}_proj.{weight,scales,biases}
                                                             (INT4, group_size 32, mode "affine")

Only the numbered-expert MoE tensors are pre-quantized; everything else in
the MTP head (attention, norms, fc, router gate, shared expert) stays in the
model's native float dtype (BF16 in the reference checkpoint), matching the
sidecar's own stated policy ("keep plain MTP tensors BF16").
"""
DEFAULT_MTP_SIDECAR_FILENAME = ...
DEFAULT_MTP_GROUP_SIZE = ...
DEFAULT_MTP_BITS = ...
DEFAULT_MTP_QUANTIZATION_MODE = ...
_LAYER_INDEX_RE = ...
_EXPERT_INDEX_RE = ...
def read_safetensors_header(path: Union[str, Path]) -> Dict[str, Any]:
    """Read just the JSON header of a ``.safetensors`` file (no tensor data).

    Useful for inspecting a sidecar file's tensor names/dtypes/shapes without
    loading the (potentially large) tensor data, e.g. in tests or tooling.
    """
    ...

def load_mtp_head(model_path: Union[str, Path], model: nn.Module, *, mtp_file: Optional[str] = ..., group_size: int = ..., bits: int = ..., mode: str = ...) -> nn.Module:
    """Attach and populate an MTP head from a sidecar ``mtp.safetensors`` file.

    Works whether or not ``model`` was already constructed with an MTP head
    (i.e. regardless of whether its config set ``mtp_num_hidden_layers > 0``):
    if the model has no ``mtp`` submodule yet, one is created here, sized from
    the sidecar file's own tensor shapes and the model's existing
    ``TextModelArgs`` (hidden_size, num_experts, moe_intermediate_size, etc.
    are assumed shared between the backbone and the MTP head, per the
    Qwen3.5/3.6 MTP convention).

    Args:
        model_path: Local directory containing the sidecar file, or a
            Hugging Face repo id to download it from. If a local directory is
            given, it must already contain the sidecar file -- this function
            does not download or re-load the main model shards.
        model: A model previously constructed via ``mlx_lm.load`` /
            ``mlx_lm.utils.load_model`` for the same checkpoint (a
            ``qwen3_5.Model``, ``qwen3_5_moe.Model``, or bare
            ``qwen3_5.TextModel`` instance).
        mtp_file: Sidecar filename, relative to the resolved model directory.
            Defaults to ``config.json``'s ``mlx_lm_extra_tensors.mtp_file`` if
            present, else ``"mtp.safetensors"``.
        group_size: Quantization group size for the sidecar's pre-quantized
            per-expert MoE weights. Default: ``32`` (MTPLX's convention).
        bits: Quantization bit-width for the sidecar's pre-quantized
            per-expert MoE weights. Default: ``4`` (MTPLX's convention).
        mode: Quantization mode used by ``mx.quantize``. Default: ``"affine"``.

    Returns:
        The same ``model`` instance, mutated in place: ``model.mtp`` (or
        ``model.language_model.mtp``) is created/populated from the sidecar.

    Raises:
        FileNotFoundError: If the sidecar file cannot be found.
        ValueError: If the sidecar's tensor names don't match the expected
            "mtp." prefix convention, or if an existing MTP head's layer count
            doesn't match the sidecar file.
    """
    ...

